### ISSUE TITLE
print () issue in the main.py file

### ISSUE THREAD

**Issue by sha70** [adpoe/Airport-Simulation.py#1]
Hi, I am very new to python, and I tried to run your simulation. But it says "SyntaxError: Missing parantheses in call to 'print'. Did you mean (int "UNIVERSITY OF PITTSBURGH - SPRING 2016:: CS1538, Assignment #4")?
This is keeping me from running your program. How do I fix this?

**Comment by adpoe** [comment]
Hi, sha70 -- which version of Python are you using?

It's been awhile since I've looked at this project -- but it was written in Python 2.7.

If you're using Python 3.0 or higher, then all calls that look like this:
      `print 'something'`

Must be changed to:
        `print('something')`

You just need to add parentheses around the string that is the target for printing.

Hope that helps!

**Comment by adpoe** [comment]
Also, if you do make those changes and they work -- feel free to issue a pull request.

Much appreciated,
T

**Comment by sha70** [comment]
Hi,
Thank you for such a prompt reply. I just started Python, so i am using 3.xx version. Yes, I was actually in the process of adding parantheses.. Good! Thank you very much your code will help me a lot with my project.

Susie

Get Outlook for Android

________________________________

**Comment by sha70** [comment]
Also, there is no source code for Queue :(

Get Outlook for Android

________________________________

**Comment by adpoe** [comment]
I believe it's this Python built-in:
https://docs.python.org/2/library/queue.html
